# Generated by Django 5.1.15 on 2026-04-14 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "materials",
            "0003_alter_course_options_course_description_course_owner_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Последнее уведомление"),
        ),
    ]
